### ISSUE TITLE
Sorted drop-downs

### ISSUE THREAD

**Issue by tinymoth** [ReadyElbow/RiskBloX#1]
Hi,

When a user wishes to select individual items from the Additional Filters drop-downs, they would be easier to search and select if the lists were alphanumerically sorted. Where this might be less true is the Tactics, as they could follow a kill-chain order, although there are more listed than the classic kill-chain. 

Thanks,
Tim

**Comment by ReadyElbow** [comment]
Hi Tim,
Alphanumeric sorting can be implemented; I'll get this added to Platforms, Threat Groups and Malware. The tactics are pulled from Mitre and I presume the reasoning for a larger number of tactics compared to classic kill-chain is to provide a more granular view into the steps/path an attacker may take.

**Comment by ReadyElbow** [comment]
Following on sorting has been introduced on the filters Platforms, Threat Groups and Malware

**Comment by ReadyElbow** [comment]
Sorting of ATT&CK Tactics according to the Mitre Kill Chain has been implemented.
