### ISSUE TITLE
Some issues don't resize to the screen so have to scroll left and right 

### ISSUE THREAD

**Issue by jonnieb007** [ReadyElbow/RiskBloX#2]
Some techniques don't resize to the screen so have to scroll left and right  for example T1087 for Platform Azure AD 
Would be great if you could look to address 
btw great tool

**Comment by ReadyElbow** [comment]
Hi jonnieb, apologies for the delay in responding. Can you explain this issue further such as what stage of the process is this occurring (Defensive Coverage view or when filling in required information)?

**Comment by jonnieb007** [comment]
Hi 

Hopefully the attached screenshot shows the issue as I need to scroll right to access positive impact and confidence columns 


Regards
JB

**Comment by ReadyElbow** [comment]
Hi JB, I believe that this has now been fixed. If you can confirm this as I believe the issue occurred only on smaller screens I will then close the issue. Thanks
