### ISSUE TITLE
Errors when completing a RiskBlox Assessment 

### ISSUE THREAD

**Issue by jonnieb007** [ReadyElbow/RiskBloX#8]
![image001](https://user-images.githubusercontent.com/41104903/134807964-c21c97f4-1f5c-47a5-9e1d-7d7b41bc0c02.jpg)
![Capture](https://user-images.githubusercontent.com/41104903/134807968-1000004d-d55d-4adc-8e29-867e45d35c5a.PNG)

Had been using back, next and first buttons to do an assessment and then these error occurred when creating the navigator layer, not been able to reproduce

**Comment by ReadyElbow** [comment]
Do you have the downloaded JSON file of that assessment to hand so the error can be reproduced? I will try to find the time to look into the logs of the API call

**Comment by ReadyElbow** [comment]
This is because of AWS CloudFront having a hardcoded limit on URI length. This has now been overcome
